version: '3.0'

services:
  mysql:
    image: mysql
<<<<<<< HEAD
    #container_name: "mysql_dev"
=======
>>>>>>> f3bcb08 (publish完成)
    container_name: mysql_dev
    ports:
      - 3303:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
    volumes:
      - "./common/dal/mysql/sql/:/sql/"
      - "./common/dal/mysql/sql/init:/docker-entrypoint-initdb.d/"
<<<<<<< HEAD
  build:
    image: golang
    container_name: tiktok
    # depends_on:
    #   - mysql
    # command:
    #   bash  ./docker-compose.sh
    # volumes:
    #   - .:/go_tiktok_project
=======
      
  build:
    image: golang
    container_name: tiktok
>>>>>>> f3bcb08 (publish完成)
    depends_on:
      - mysql
    # stdin_open: 
    #   true
    # tty: 
    #   true
<<<<<<< HEAD
    # command:
    #   bash /go_tiktok_project/docker-compose.sh
=======
    command:
      bash /go_tiktok_project/docker-compose.sh
>>>>>>> f3bcb08 (publish完成)
    volumes:
      - .:/go_tiktok_project